# Training on medical simplification data
this notebook was continously used (and adapted) for various training setups for t5 modles for training on medical data

In [1]:
#miscellaneous imports
import requests
import os
import datetime
import random
import zipfile
import shutil
import math
import torch
from torch.utils.data import DataLoader
from torch.optim import AdamW # Changed from transformers import AdamW
import datasets as hf_datasets # Alias to avoid conflict with local variables
import transformers as hf_transformers # Alias
from datasets import Dataset, DatasetDict, load_dataset
from transformers import T5Tokenizer, T5TokenizerFast, T5ForConditionalGeneration, set_seed, get_scheduler
from accelerate import Accelerator, notebook_launcher
from tqdm.notebook import tqdm # Or from tqdm import tqdm
import importlib.metadata # For version checking
from transformers import (
    T5Tokenizer,
    T5ForConditionalGeneration,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    DataCollatorForSeq2Seq,
    set_seed
)
import nltk
import numpy as np

import error: No module named 'triton'

# Download the data (ctrl + 'a' then ctrl + '/')

In [ ]:
# user = "SebaJoe"
# repo = "MultiCochrane"
# branch = "main" 
# path_to_dir = "data/MultiCochrane"

# filenames = [
#     "multiCochrane_all.zip"
# ]

# local_dir = "./data"

# try:
#     os.makedirs(local_dir, exist_ok=True)
#     print(f"Directory '{local_dir}' ensured.")
# except OSError as e:
#     print(f"Error creating directory {local_dir}: {e}")
#     filenames = [] 

# download_count = 0
# error_count = 0
# for filename in filenames:
#     raw_url = f"https://raw.githubusercontent.com/{user}/{repo}/{branch}/{path_to_dir}/{filename}"
#     local_filepath = os.path.join(local_dir, filename)
#     try:
#         response = requests.get(raw_url, stream=True) 
#         response.raise_for_status() 
#         with open(local_filepath, 'wb') as f:
#             for chunk in response.iter_content(chunk_size=8192):
#                 f.write(chunk)
#         download_count += 1
#     except Exception as e:
#         print(f"Error {filename}: {e}")
#         error_count += 1


# def unzip_file(zip_file_path, extract_to_dir):
#     try:
#         os.makedirs(extract_to_dir, exist_ok=True)
#     except OSError as e:
#         print(f"Error{extract_to_dir}: {e}")
#         return 

#     print(f"extracting '{zip_file_path}' to '{extract_to_dir}'...")
#     try:
#         with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
#             zip_ref.extractall(extract_to_dir)
#     except Exception as e:
#         print(f"error {e}")


# path_to_my_zip = local_dir + "/" + filenames[0] 
# destination_folder = local_dir + "/multiCochrane_all"
# unzip_file(path_to_my_zip, destination_folder)
# print("ready freddy")

# Load the unfiltered english data (multiCochrane_all)
put it in transformers/datasets suitable format

In [2]:
import os
import sys
from pathlib import Path
from datasets import load_dataset

_root = next(p for p in [Path.cwd().resolve(), *Path.cwd().resolve().parents] if (p / "src" / "paths.py").exists())
sys.path.insert(0, str(_root / "src"))
from paths import MULTICOHRANE_EN_UNFILTERED

base_path = str(MULTICOHRANE_EN_UNFILTERED)
data_files = {
    "train": os.path.join(base_path, "train0_en.csv"),
    "test": os.path.join(base_path, "test0_en.csv"),
    "validation": os.path.join(base_path, "val0_en.csv")
}
multi_cochrane_dataset = load_dataset("csv", data_files=data_files)
print("\nDataset loaded successfully:")
print(multi_cochrane_dataset)

Dataset loaded successfully:
DatasetDict({
    train: Dataset({
        features: ['Unnamed: 0', 'prefix', 'input_text', 'target_text', 'doi'],
        num_rows: 61194
    })
    validation: Dataset({
        features: ['Unnamed: 0', 'prefix', 'input_text', 'target_text', 'doi'],
        num_rows: 83
    })
    test: Dataset({
        features: ['Unnamed: 0', 'prefix', 'input_text', 'target_text', 'doi'],
        num_rows: 395
    })
})

In [68]:
multi_cochrane_dataset['train'][5]

{'Unnamed: 0': 9,
 'prefix': 'simplify: ',
 'input_text': 'One study, the European Organisation for Research and Treatment of Cancer (EORTC) trial, demonstrated a statistically significant overall survival (OS) benefit for RT plus PCV, with a median OS of 3.5 years compared with 2.6 years in the RT alone arm (P value = 0.018).',
 'target_text': 'One study was able to demonstrate a significant survival benefit for the addition of chemotherapy to radiotherapy after surgery, compared with radiotherapy alone.',
 'doi': '10.1002/14651858.CD007104.pub2'}

# Add a prefix to the training data for speficiying simplificatio task

In [3]:
prefix = "simplify: "
def add_prefix(example):
  example['prefix'] = prefix
  return example

for split in ["train", "test", "validation"]:
    updated_train_dataset = multi_cochrane_dataset[split].map(add_prefix)
    multi_cochrane_dataset[split] = updated_train_dataset

print("Updated dataset structure:")
print(multi_cochrane_dataset)
print("\nFirst example of updated train split:")
print(multi_cochrane_dataset["train"][0])

Map:   0%|          | 0/61194 [00:00<?, ? examples/s]

Map:   0%|          | 0/395 [00:00<?, ? examples/s]

Map:   0%|          | 0/83 [00:00<?, ? examples/s]

Updated dataset structure:
DatasetDict({
    train: Dataset({
        features: ['Unnamed: 0', 'prefix', 'input_text', 'target_text', 'doi'],
        num_rows: 61194
    })
    validation: Dataset({
        features: ['Unnamed: 0', 'prefix', 'input_text', 'target_text', 'doi'],
        num_rows: 83
    })
    test: Dataset({
        features: ['Unnamed: 0', 'prefix', 'input_text', 'target_text', 'doi'],
        num_rows: 395
    })
})

First example of updated train split:
{'Unnamed: 0': 0, 'prefix': 'simplify: ', 'input_text': 'Compared to standard care, social skills training may improve the social skills of people with schizophrenia and reduce relapse rates, but at present, the evidence is very limited with data rated as very low quality.', 'target_text': 'However, at the moment evidence is very limited with data only of very low quality available.', 'doi': '10.1002/14651858.CD009006.pub2'}

# Encode using t5 tokenizer

In [4]:
# encode dataset
#based on https://colab.research.google.com/github/NielsRogge/Transformers-Tutorials/blob/master/T5/Fine_tuning_Dutch_T5_base_on_CNN_Daily_Mail_for_summarization_(on_TPU_using_HuggingFace_Accelerate).ipynb#scrollTo=tiLdcTmkg-_o
from transformers import T5Tokenizer
tokenizer = T5Tokenizer.from_pretrained("google-t5/t5-large")

max_input_length = 128
max_target_length = 128

def preprocess_examples(examples):
  input_txt = examples['input_text']
  target_txt = examples['target_text']
  prefix = examples['prefix']
  
  inputs = [prefix + inp for inp, prefix in zip(input_txt, prefix)]
  model_inputs = tokenizer(inputs, max_length=max_input_length, padding="max_length", truncation=True)

  # encode the simplifications
  labels = tokenizer(target_txt, max_length=max_target_length, padding="max_length", truncation=True).input_ids
  labels_with_ignore_index = []
  for labels_example in labels:
    labels_example = [label if label != 0 else -100 for label in labels_example]
    labels_with_ignore_index.append(labels_example)
  
  model_inputs["labels"] = labels_with_ignore_index

  return model_inputs

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

In [5]:
train_ds = multi_cochrane_dataset['train']
val_ds = multi_cochrane_dataset['validation']
test_ds = multi_cochrane_dataset['test']
encoded_train_ds = train_ds.map(preprocess_examples, batched=True, remove_columns=train_ds.column_names)
encoded_val_ds = val_ds.map(preprocess_examples, batched=True, remove_columns=val_ds.column_names)
encoded_test_ds = test_ds.map(preprocess_examples, batched=True, remove_columns=test_ds.column_names)

Map:   0%|          | 0/61194 [00:00<?, ? examples/s]

Map:   0%|          | 0/83 [00:00<?, ? examples/s]

Map:   0%|          | 0/395 [00:00<?, ? examples/s]

In [6]:
encoded_train_ds

Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 61194
})

In [7]:
encoded_train_ds['labels'][0]

[611,
 6,
 44,
 8,
 798,
 2084,
 19,
 182,
 1643,
 28,
 331,
 163,
 13,
 182,
 731,
 463,
 347,
 5,
 1,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100]

In [8]:
encoded_train_ds['input_ids'][0]

[18356,
 10,
 3,
 25236,
 12,
 1068,
 124,
 6,
 569,
 1098,
 761,
 164,
 1172,
 8,
 569,
 1098,
 13,
 151,
 28,
 31926,
 11,
 1428,
 3,
 60,
 16543,
 1917,
 6,
 68,
 44,
 915,
 6,
 8,
 2084,
 19,
 182,
 1643,
 28,
 331,
 3,
 4094,
 38,
 182,
 731,
 463,
 5,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

# Set up some default hyper parameters, initialize modle, data_collator and adamW optimzier

In [9]:
hyperparameters = {
    "learning_rate": 1e-5, 
    "num_epochs": 25, 
    "train_batch_size": 16, 
    #"gradient_accumulation_steps": 4,
    "eval_batch_size": 4, 
    "seed": 42,
    "output_dir": "./content_simplifier_t5_base_ROUGE_unfiltered_epoch_25/",
    "mixed_precision": "fp16",
}

In [11]:
#set up model and optimizer
import evaluate
model_location = r"D:\trained_models\optuna_sweep_checkpoints_t5_small_pretrained_wikilarge\run-4\checkpoint-960" 

set_seed(hyperparameters["seed"])
model = T5ForConditionalGeneration.from_pretrained(model_location)
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)
optimizer = AdamW(model.parameters(), lr=hyperparameters["learning_rate"])
#sari_metric = evaluate.load("sari")
nltk.download("punkt", quiet=True)
metric = evaluate.load("rouge")

# Sari metric eval
metric used for evalutation of simplification task

In [ ]:
sari_metric = evaluate.load("sari")
def compute_metrics_sari(eval_preds):
    predictions, labels, inputs = eval_preds.predictions, eval_preds.label_ids, eval_preds.inputs
    predictions = np.clip(predictions, 0, tokenizer.vocab_size - 1)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    inputs = np.where(inputs != -100, inputs, tokenizer.pad_token_id)
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    decoded_inputs = tokenizer.batch_decode(inputs, skip_special_tokens=True)
    all_refs = [[lbl] for lbl in decoded_labels]
    sari_results = sari_metric.compute(
        sources=decoded_inputs,
        predictions=decoded_preds,
        references=all_refs
    )
    return {"sari": sari_results["sari"]}

# Rouge metric eval
(old, but kept for archival/experimental purposese)

In [13]:
# #https://huggingface.co/docs/evaluate/en/transformers_integrations
# import nltk
# nltk.download('punkt_tab')
# def compute_metrics_rouge(eval_preds):
#     preds, labels = eval_preds

#     # Zorg ervoor dat preds en labels geldige token-ID's bevatten
#     preds = np.clip(preds, 0, tokenizer.vocab_size - 1)  # Beperk tot geldige range
#     labels = np.where(labels == -100, tokenizer.pad_token_id, labels)  # Vervang -100 door pad_token_id

#     # Decode de voorspellingen en labels
#     decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
#     decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

#     # Voeg newlines toe voor rougeLSum
#     decoded_preds = ["\n".join(nltk.sent_tokenize(pred.strip())) for pred in decoded_preds]
#     decoded_labels = ["\n".join(nltk.sent_tokenize(label.strip())) for label in decoded_labels]

#     # Bereken de ROUGE-score
#     result = metric.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
#     return result

# run below for training for speficic hyperparameters, but skip for sweep

In [14]:
# training_args = Seq2SeqTrainingArguments(
#     output_dir=hyperparameters["output_dir"],
#     overwrite_output_dir=True,
#     evaluation_strategy="epoch",
#     save_strategy="epoch",
#     num_train_epochs=hyperparameters["num_epochs"],
#     learning_rate=hyperparameters["learning_rate"],
#     lr_scheduler_type="linear",
#     warmup_steps=500,
#     per_device_train_batch_size=16, 
#     per_device_eval_batch_size=16,
#     weight_decay=0.01,
#     predict_with_generate=True,
#     include_inputs_for_metrics=True,
#     gradient_accumulation_steps=2,
#     generation_max_length=128,
#     load_best_model_at_end=True,
#     optim="adamw_torch",
#     fp16=True,
#     label_smoothing_factor=0.1,
#     metric_for_best_model="sari",
#     greater_is_better=True,
#     report_to = "none")

In [15]:
# trainer = Seq2SeqTrainer(
#     model=model,
#     args=training_args,
#     train_dataset=encoded_train_ds,
#     eval_dataset=encoded_val_ds,
#     data_collator=data_collator,
#     tokenizer=tokenizer,
#     compute_metrics=compute_metrics_sari
# )

In [16]:
# train_result = trainer.train()
# trainer.save_model(training_args.output_dir)

In [17]:
# import torch
# i=1
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# prompt = f"Simplify text: {multi_cochrane_dataset["train"][i]["input_text"]}"
# inputs = tokenizer(prompt, return_tensors="pt").to(device)
# generated_ids = trainer.model.generate(**inputs, max_length=max_target_length, do_sample=True, top_p=0.95, temperature=0.1)
# summary = tokenizer.decode(generated_ids[0], skip_special_tokens=True)
# print(f"original: {multi_cochrane_dataset["train"][i]["input_text"]}") 
# print("Simplified:", summary)

# hyperparameter sweep using optuna

In [ ]:
hyperparameters

Often start runs form here, so for safety, reiinit everything

In [ ]:
import evaluate
set_seed(hyperparameters["seed"])
model_location = r"D:\trained_models\optuna_sweep_checkpoints_t5_small_pretrained_wikilarge\run-4\checkpoint-960" 
model = T5ForConditionalGeneration.from_pretrained(model_location)
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)
optimizer = AdamW(model.parameters(), lr=hyperparameters["learning_rate"])
sari_metric = evaluate.load("sari")
# nltk.download("punkt", quiet=True)
# metric = evaluate.load("rouge")

In [ ]:
#general hyperparameters, basically set according to the GPU performance, model size and data size
hyperparameters = {
    "train_batch_size": 64,
    "eval_batch_size": 64, 
    "seed": 42,
    "mixed_precision": "fp16", 
    "gradient_accumulation_steps": 2,
}
set_seed(hyperparameters["seed"])

In [15]:
training_args = Seq2SeqTrainingArguments(
    output_dir="./optuna_sweep_checkpoints_t5_small_pretrained_wikilarge", 
    overwrite_output_dir=True,
    eval_strategy="epoch",
    save_strategy="epoch",
    per_device_train_batch_size=hyperparameters["train_batch_size"],
    per_device_eval_batch_size=hyperparameters["eval_batch_size"],
    predict_with_generate=True,
    include_for_metrics=["inputs"],
    gradient_accumulation_steps=hyperparameters["gradient_accumulation_steps"],
    generation_max_length=128,
    load_best_model_at_end=True, 
    optim="adamw_torch",
    fp16=True,
    metric_for_best_model="sari",
    greater_is_better=True,      
    report_to="none",              
    seed=hyperparameters["seed"],  
    save_total_limit=1            
)

In [16]:
trainer = Seq2SeqTrainer(
    args=training_args,
    model_init=model_init, 
    train_dataset=encoded_train_ds,
    eval_dataset=encoded_val_ds,
    data_collator=data_collator,
    processing_class=tokenizer,
    compute_metrics=compute_metrics_sari
)

In [17]:
N_TRIALS = 20
print(f"Starting hyperparameter search with {N_TRIALS} trials...")

study = optuna.create_study(
    direction="maximize",
    study_name="t5-large-sari-sweep", 
)

[I 2025-04-10 15:26:53,360] A new study created in memory with name: t5-large-sari-sweep

Starting hyperparameter search with 20 trials...

In [18]:
best_run = trainer.hyperparameter_search(
    direction="maximize",               # We want to maximize SARI
    backend="optuna",                   # Use Optuna backend
    hp_space=hp_space,                  # Function defining the search space (Trainer will pass trial to it)
    n_trials=N_TRIALS,                  # Number of trials for the Trainer to run
    compute_objective=compute_objective, # Function to get the objective value from metrics
    study_name="t5-sari-sweep",         # Optional: Name the study managed internally by Trainer
    load_if_exists=True,                # Optional: Resume the study if storage exists

)

[I 2025-04-10 15:26:55,864] A new study created in memory with name: t5-sari-sweep
Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.48.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.

[W 2025-04-10 15:27:20,619] Trial 0 failed with parameters: {'learning_rate': 0.0002862961213247954, 'num_train_epochs': 4, 'weight_decay': 0.04322940045181294, 'label_smoothing_factor': 0.16314435776067657, 'warmup_steps': 723, 'lr_scheduler_type': 'linear'} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "c:\Users\Ruben\GPUcodig\AIenv\Lib\site-packages\optuna\study\_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "c:\Users\Ruben\GPUcodig\AIenv\Lib\site-packages\transformers\integrations\integration_utils.py", line 254, in _objective
    trainer.train(resume_from_checkpoint=checkpoint, trial=trial)
  File "c:\Users\Ruben\GPUcodig\AIenv\Lib\site-packages\transformers\trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ruben\GPUcodig\AIenv\Lib\site-packages\transformers\trainer.py", line 2556, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ruben\GPUcodig\AIenv\Lib\site-packages\transformers\trainer.py", line 3764, in training_step
    self.accelerator.backward(loss, **kwargs)
  File "c:\Users\Ruben\GPUcodig\AIenv\Lib\site-packages\accelerate\accelerator.py", line 2325, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "c:\Users\Ruben\GPUcodig\AIenv\Lib\site-packages\torch\_tensor.py", line 626, in backward
    torch.autograd.backward(
  File "c:\Users\Ruben\GPUcodig\AIenv\Lib\site-packages\torch\autograd\__init__.py", line 347, in backward
    _engine_run_backward(
  File "c:\Users\Ruben\GPUcodig\AIenv\Lib\site-packages\torch\autograd\graph.py", line 823, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[W 2025-04-10 15:27:20,627] Trial 0 failed with value None.

KeyboardInterrupt:

In [ ]:
print("Hyperparameter search finished.")

print(f"Best run found: Run ID {best_run.run_id}") 
print(f"Best SARI score: {best_run.objective}")
print("Best hyperparameters:")
print(best_run.hyperparameters)

Hyperparameter search finished.
Best run found: Run ID 17
Best SARI score: 42.61698282898968
Best hyperparameters:
{'learning_rate': 0.00013795652077000847, 'num_train_epochs': 5, 'weight_decay': 0.039744046312776046, 'label_smoothing_factor': 0.16026143407163396, 'warmup_steps': 774, 'lr_scheduler_type': 'constant_with_warmup'}

In [ ]:
#set it manually to the best hyperparameters (had difficulties loading it from checkpoint)
best_hyperparameters = {
    "learning_rate": 0.0003087545189866897,
    "num_train_epochs": 15, 
    "lr_scheduler_type": "constant_with_warmup",
    "warmup_steps": 789, 
    "weight_decay": 0.057960328420691556,
    "label_smoothing_factor": 0.1548218707925769,
}

In [ ]:
#train the final model with the best hyperparameters
print("\nTraining final model with best hyperparameters...")
if best_hyperparameters is None:
     raise RuntimeError("Hyperparameter search did not return best hyperparameters.")
print(f"Applying best hyperparameters: {best_hyperparameters}")
final_output_dir = "./final_t5_small_opt_sweep_pretrained_wiki_run4_check960_RUN2/" 
final_training_args = Seq2SeqTrainingArguments(
    output_dir=final_output_dir,
    overwrite_output_dir=True,
    eval_strategy="epoch",
    save_strategy="epoch",
    per_device_train_batch_size=hyperparameters["train_batch_size"],
    per_device_eval_batch_size=hyperparameters["eval_batch_size"],
    predict_with_generate=True,
    include_for_metrics=["inputs"],
    gradient_accumulation_steps=2,
    generation_max_length=128,
    load_best_model_at_end=True,
    optim="adamw_torch",
    fp16=(hyperparameters["mixed_precision"] == "fp16"),
    metric_for_best_model="sari",
    greater_is_better=True,
    report_to="tensorboard",
    seed=hyperparameters["seed"],
    save_total_limit=2, 
    logging_strategy="steps", 
    logging_steps=100,
    num_train_epochs=30,#best_hyperparameters["num_train_epochs"],
    learning_rate=best_hyperparameters["learning_rate"],
    lr_scheduler_type=best_hyperparameters["lr_scheduler_type"],
    warmup_steps=best_hyperparameters["warmup_steps"],
    weight_decay=best_hyperparameters["weight_decay"],
    label_smoothing_factor=best_hyperparameters["label_smoothing_factor"],
)


final_trainer = Seq2SeqTrainer(
    model=model_init(None), 
    args=final_training_args,
    train_dataset=encoded_train_ds,
    eval_dataset=encoded_val_ds,
    data_collator=data_collator,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics_sari
)


print("Starting final training run...")
train_result = final_trainer.train()
print("Final training complete.")

final_trainer.save_model(final_output_dir)
final_trainer.save_state() # Save optimizer state etc.
tokenizer.save_pretrained(final_output_dir)
print(f"Final best model saved to {final_output_dir}")

Training final model with best hyperparameters...
Applying best hyperparameters: {'learning_rate': 0.0003087545189866897, 'num_train_epochs': 15, 'lr_scheduler_type': 'constant_with_warmup', 'warmup_steps': 789, 'weight_decay': 0.057960328420691556, 'label_smoothing_factor': 0.1548218707925769}

C:\Users\Ruben\AppData\Local\Temp\ipykernel_41360\1966569801.py:50: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  final_trainer = Seq2SeqTrainer(

Starting final training run...

There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight', 'lm_head.weight'].

Final training complete.
Final best model saved to ./final_t5_small_opt_sweep_pretrained_wiki_run4_check960_RUN2/

In [61]:
multi_cochrane_dataset['train'][0]

{'Unnamed: 0': 0,
 'prefix': 'simplify: ',
 'input_text': 'Compared to standard care, social skills training may improve the social skills of people with schizophrenia and reduce relapse rates, but at present, the evidence is very limited with data rated as very low quality.',
 'target_text': 'However, at the moment evidence is very limited with data only of very low quality available.',
 'doi': '10.1002/14651858.CD009006.pub2'}

In [88]:
input_dir = final_output_dir

In [ ]:
#final_output_dir = r"C:\Users\Ruben\GPUcodig\LM\medical_project_simplification\optuna_sweep_checkpoints_t5_large\run-0\checkpoint-7650"
device = torch.cuda.current_device() if torch.cuda.is_available() else "cpu"
model = T5ForConditionalGeneration.from_pretrained(final_output_dir).to(device)
tokenizer = T5Tokenizer.from_pretrained("google-t5/t5-large")

for i in range(1000):
    prompt = f"simplify: {multi_cochrane_dataset['train'][i]['input_text']}"
    inputs = tokenizer(prompt, return_tensors="pt").to(device)
    generated_ids = model.generate(**inputs,
                                    max_length=128, 
                                    temperature=0.7,
                                    num_beams=50)#,
                                    #length_penalty=1.0,
                                    #no_repeat_ngram_size=5)
    summary = tokenizer.decode(generated_ids[0], skip_special_tokens=True)
    print(f"Original: {multi_cochrane_dataset['train'][i]['input_text']}")
    print(f"Simplified: {summary}\n\n")

Original: Compared to standard care, social skills training may improve the social skills of people with schizophrenia and reduce relapse rates, but at present, the evidence is very limited with data rated as very low quality.
Simplified: Compared to standard care, social skills training may improve the social skills of people with schizophrenia and reduce relapse rates.


Original: Four out of 52 studies, including 128 CCS, assessed the prevalence of hypomagnesaemia, which ranged between 13.2% and 28.6%.
Simplified: Four out of 52 studies, including 128 CCS, assessed the prevalence of hypomagnesaemia, which ranged between 13.2% and 28.6%.


Original: Seven RCTs including 960 participants were identified.
Simplified: The review authors identified seven randomised controlled trials (RCTs) including 960 participants that compared L-ornithine L-ornithine L-ornithine L-ornithine L-ornithine L-ornithine L-ornithine L-ornithine L-ornithine L-ornithine L-ornithine L-ornithine L-ornithine L-ascites.


Original: Brackets (metal squares) are usually attached to teeth other than molars, where bands (metal rings that go round each tooth) are more commonly used.
Simplified: Brackets (metal squares) are usually attached to teeth other than molars, where bands (metal rings that go round each tooth) are more commonly used.


Original: Many controlled trials have been undertaken to investigate its efficacy.
Simplified: Many randomised controlled trials have been undertaken to investigate its efficacy.


Original: One study, the European Organisation for Research and Treatment of Cancer (EORTC) trial, demonstrated a statistically significant overall survival (OS) benefit for RT plus PCV, with a median OS of 3.5 years compared with 2.6 years in the RT alone arm (P value = 0.018).
Simplified: One study, the European Organisation for Research and Treatment of Cancer (EORTC) trial, demonstrated a statistically significant overall survival benefit for RT plus PCV, with a median survival of 3.5 years compared with 2.6 years in the RT alone arm.


Original: Only seven studies reported live birth or ongoing pregnancy.
Simplified: Only seven studies reported live birth or ongoing pregnancy.


Original: Loss to follow-up from randomised trials can introduce bias and reduce study power, affecting the generalisability, validity and reliability of results.
Simplified: The Loss to follow-up of trials can cause bias and reduce study power, affecting the generalisability, validity and reliability of results.


Original: We were unable to pool data for dental aesthetics, patient-reported pain and discomfort, periodontal health and treatment time; however, individual studies did not find any differences between the surgical techniques (low- to very low-quality evidence).
Simplified: We were unable to pool data for aesthetics, patient-reported pain and discomfort, periodontal health and treatment time (low- to very low-quality evidence).


Original: These evaluated social skills programmes versus standard care, or discussion group.
Simplified: These evaluated social skills programmes versus standard care, or discussion group.


Original: Milder regimens (using lower doses of steroids) are safe and effective in moderate BP.
Simplified: Milder regimens of steroids are safe and effective in moderate BP.


Original: Results are based upon the findings of several (five) trials that included an "open lung ventilation strategy", whereby the intervention group differed from the control group in aspects other than the recruitment manoeuvre (including co-interventions such as higher PEEP, different modes of ventilation and higher plateau pressure), making interpretation of the results difficult.
Simplified: Results are based on the findings of five trials that included an "open lung ventilation strategy", whereby the intervention group differed from the control group in aspects other than the recruitment manoeuvre (including co-interventions such as higher PEEP, different modes of ventilation and higher plateau pressure), making interpretation of the results difficult.


Original: To assess the effects of interventions to alter the length of primary care physicians' consultations.
Simplified: The aim of this Cochrane Review was to find out if changing the length of time that primary care physicians consult with patients is effective.


Original: APD did not differ from CAPD with respect to mortality (RR 1.49, 95% CI 0.51 to 4.37), risk of peritonitis (RR 0.75, 95% CI 0.50 to 1.11), switching from original PD modality to a different dialysis modality (RR 0.50, 95% CI 0.25 to 1.02), hernias (RR 1.26, 95% interval 0.32 to 5.01), PD fluid leaks (RR 1.06, 95% CI 0.11 to 9.83), PD catheter removal (RR 0.64, 95% CI 0.27 to 1.48) or hospital admissions (RR 0.96, 95% CI 0.43 to 2.17).
Simplified: APD did not differ from CAPD with respect to mortality, peritonitis, switching from original PD modality to a different dialysis modality, hernias, PD fluid leaks or hospital admissions.


Original: Although low-quality evidence suggests that professional oral care could reduce mortality due to pneumonia in nursing home residents when compared to usual care, this finding must be considered with caution.
Simplified: There is low-quality evidence that professional mouth care may reduce the risk of pneumonia when compared to usual mouth care.


Original: Treatment with ACEi or ARB (2 studies, 1368 participants: RR 0.90, 95% CI 0.43 to 1.90; I2 = 97%; very low certainty evidence) had uncertain effects on hospitalisation for heart failure, as treatment estimates were consistent with either benefit or harm.
Simplified: Treatment with ACEi or ARB (2 studies, 1368 participants) had uncertain effects on hospitalisation for heart failure, as treatment estimates were consistent with either benefit or harm.


Original: There was no significant effect on mortality with co-trimoxazole or isoniazid prophylaxis (RR 0.82, 0.46 to 1.46, I2 statistic = 76%, P value = 0.58); however, analysis of one study that used co-trimoxazole showed a significant reduction in mortality (RR 0.67, 95% CI 0.53 to 0.85, P value = 0.001).
Simplified: However, analysis of one study that used co-trimoxazole showed a significant reduction in mortality.


Original: For this update, we searched the Cochrane Schizophrenia Group's register of trials (November 2012).
Simplified: The Information Specialist of Cochrane Schizophrenia ran an electronic search of the Cochrane Schizophrenia Group's register of trials (November 2012).


Original: NHAP may be caused by aspiration of oropharyngeal flora into the lung, and by failure of the individual's defence mechanisms to eliminate the aspirated bacteria.
Simplified: NHAP can be caused by infection with oropharyngeal flora (oropharyngeal flora) into the lung.


Original: A non-eligible study also found long follow-up time as risk factor.
Simplified: Another non-eligible study found long follow-up time as risk factor.


Original: Though there is insufficient evidence to confirm a better functional outcome, external fixation reduces redisplacement, gives improved anatomical results and most of the excess surgically-related complications are minor.
Simplified: Although there is insufficient evidence to confirm a better functional outcome, external fixation reduces redisplacement, gives improved anatomical results and most of the excess surgically-related complications are minor.


Original: We could not say whether more people who had a remote check-up needed oral corticosteroids for an asthma exacerbation than those who were seen face-to-face because the confidence intervals (CIs) were very wide (OR 1.74, 95% CI 0.41 to 7.44; 278 participants; one study; low quality evidence).
Simplified: We could not say whether or not people who had a check-up over the phone or internet were more likely to need oral corticosteroids for an asthma attack than those seen face-to-face.


Original: In less severe cases, non-surgical interventions may be considered, however few medical alternatives are currently available.
Simplified: In less severe cases, non-surgical interventions may be considered, however few medical alternatives are currently available.


Original: We included seven studies, with 766 participants: four used intracutaneous injections, two subcutaneous, and one both.
Simplified: We included seven studies, with 766 participants: four used intracutaneous injections, two subcutaneous, and one both.


Original: Properly designed and executed randomised trials are necessary.
Simplified: Properly designed and executed randomised trials are necessary.


Original: External fixation maintained reduced fracture positions (redisplacement requiring secondary treatment: 7/356 versus 51/338 (data from 9 trials); relative risk 0.17, 95% confidence interval 0.09 to 0.32) and prevented late collapse and malunion compared with plaster cast immobilisation.
Simplified: The review found that external fixation reduced fracture redisplacement requiring further treatment and prevented late collapse and malunion compared with plaster cast immobilisation.


Original: Cochrane Oral Health’s Information Specialist searched the following databases: Cochrane Oral Health’s Trials Register (to 15 November 2017), the Cochrane Central Register of Controlled Trials (CENTRAL) (the Cochrane Library, 2017, Issue 10), MEDLINE Ovid (1946 to 15 November 2017), and Embase Ovid (1980 to 15 November 2017) and Cumulative Index to Nursing and Allied Health Literature (CINAHL; 1937 to 15 November 2017).
Simplified: We searched scientific databases for randomised controlled trials (clinical studies where people are randomly put into one of two or more treatment groups) published up to 15 November 2017.


Original: We also searched registers of clinical trials and abstracts of scientific meetings.
Simplified: We searched electronic databases and other resources for randomised controlled trials (a type of study in which participants are assigned to one of two or more treatment groups using a random method) or quasi-randomised controlled trials (a type of study in which participants are assigned to one of two or more treatment groups using a random method) that compared the efficacy and safety of L-ornithine L-ornithine L-ornithine L-ornithine L-aspartate with placebo.


Original: Application of the findings of this review would depend on trial setting, population, disease area, data collection and follow-up procedures.
Simplified: The application of these findings would depend on trial setting, population, disease area, data collection and follow-up procedures.


Original: However, all studies were scored as having high risk of bias, reflecting the observational nature of the research and the use of an uncontrolled study design.
Simplified: However, all studies were scored as having high risk of bias, reflecting the observational nature of the research and the use of an uncontrolled study design.


Original: No studies evaluated oral care versus no oral care.
Simplified: No studies evaluated oral care versus no oral care.


Original: However, these interventions are of uncertain benefit and may increase the risk of harm, such as hypotension and electrolyte abnormalities, in those with CKD.
Simplified: However, these interventions are of uncertain benefit and may increase the risk of harm, such as hypotension and electrolyte abnormalities, in those with chronic kidney disease.


Original: SU (with or without metformin) gave poorer metabolic control compared to insulin alone (mean difference in glycosylated haemoglobin A1c (HbA1c) from baseline to end of study, for insulin compared to oral therapy: -1.3% (95% confidence interval (CI) -2.4 to -0.1; P = 0.03, 160 participants, four studies, follow-up/duration of therapy: 12, 30, 36 and 60 months; however, heterogeneity was considerable).
Simplified: However, we found that the drug sulphonylurea (like glibenclamide or glyburide, gliclazide) gave poorer metabolic control compared to the drug sulphonylurea (like glibenclamide or glyburide, gliclazide) alone.


Original: We included randomised controlled trials of asthma education for children who had attended the emergency department for asthma, with or without hospitalisation, within the previous 12 months.
Simplified: We searched scientific databases for randomised controlled trials (clinical studies where people are randomly put into one of two or more treatment groups) looking at the effects of asthma education for children who had attended the emergency department for asthma, with or without hospitalisation, within the previous 12 months.


Original: food product reformulation, food procurement policy in specific settings).
Simplified: The review authors searched the medical literature for randomised controlled trials (RCTs) and quasi-RCTs (a type of study in which participants are assigned to one of two or more treatment groups using a random method) looking at the effects of reformulation versus usual care (where participants are allocated to one of two or more treatment groups using a random method) looking at the effects of reformulation versus usual care (where allocation is not really random, e.g.


Original: We judged the risk of bias to be high for both studies and the overall quality of the evidence was low/very low for all outcomes, as assessed using the GRADE approach.
Simplified: We judged the risk of bias to be high for both studies and the overall quality of the evidence was low/very low for all outcomes, as assessed using the GRADE approach.


Original: The extent and quality of evidence guiding treatment choice for this condition are uncertain.
Simplified: The certainty of the evidence guiding treatment choice for people with rheumatoid arthritis is low.


Original: Antibiotics could be beneficial in preventing LRTIs in high-risk children, and may also help prevent school absenteeism and work days missed by children and/or carers.
Simplified: Antibiotics may be beneficial in preventing LRTI in high-risk children, and may also help prevent school absenteeism and work days missed by children and/or carers.


Original: Sleep bruxism is an oral activity characterized by involuntary teeth grinding or clenching during sleep.
Simplified: Sleep bruxism is an oral activity characterized by involuntary teeth grinding or clenching during sleep.


Original: All trials used probiotics as adjuvant therapy to antifungal drugs.
Simplified: All trials compared oral fluconazole (antifungal medicine) with oral fluconazole plus oral fluconazole plus oral fluconazole plus oral fluconazole plus oral fluconazole plus oral fluconazole plus oral fluconazole plus oral fluconazole plus oral fluconazole plus oral fluconazole plus oral fluconazole plus oral fluconazole plus oral fluconazole plus oral fluconazole plus oral fluconazole plus oral fluconazole plus oral antibiotics.


Original: There was insufficient evidence on the effectiveness of pharmacotherapy for the treatment of sleep bruxism.
Simplified: There was insufficient evidence on the effectiveness of pharmacotherapy for the treatment of sleep bruxism.


Original: For the current review we only included studies that were conducted on samples from community settings, and excluded studies that were conducted in primary care or secondary care settings.
Simplified: For the current review we only included studies that were conducted on samples from community settings, and excluded studies that were conducted in primary or secondary care settings.


Original: Therefore, we judged the overall quality of evidence as very low according to the GRADE approach.
Simplified: Quality of the evidence


Original: There was moderate evidence that lumbar supports are not more effective than no intervention or training in preventing low-back pain, and conflicting evidence whether lumbar supports are effective supplements to other preventive interventions.
Simplified: Prevention: There was little or no difference between people with low-back pain who used back supports and those who received no treatment in short-term pain reduction or overall improvement.


Original: All were conducted in the UK, and tested short-term changes in the consultation time allocated to each patient.
Simplified: All studies tested short-term changes in the consultation time allocated to each patient.


Original: Furthermore, with retrospective evaluation of biomarkers, codeletion of complete chromosome arms 1p and 19q and IDH-1 or -2 mutation were independent prognostic factors for OS in two of the RCTs (Radiation Therapy Oncology Group (RTOG) and EORTC), and were predictive for OS in one trial (RTOG).
Simplified: In addition, during examination of these brain tumour biopsy specimens, they found specific chromosome deletions and mutations in two studies (Radiation Therapy Oncology Group (RTOG) and EORTC).


Original: No studies reported on adverse events (other than miscarriage) or drug reactions.
Simplified: No studies reported on side effects (other than miscarriage) or drug reactions.


Original: Therapeutic ultrasound may be offered to people experiencing mild to moderate symptoms of carpal tunnel syndrome (CTS).
Simplified: In people with mild to moderate symptoms of CTS, therapeutic ultrasound may be offered to people with mild to moderate symptoms.


Original: The effects of ACEi or ARB, or aldosterone antagonists on worsening heart failure or kidney function, hypotension, or quality of life were uncertain due to sparse data or were not reported.
Simplified: The effects of ACEi or ARB, or aldosterone antagonists on worsening heart failure or kidney function, hypotension, or quality of life were uncertain due to sparse data or were not reported.


Original: We downgraded the evidence for the pneumonia outcome to low.
Simplified: We rated the quality of the evidence from studies using four levels: very low (further research is very likely to have an important impact on our confidence in the estimate of effect and is likely to change the estimate), low (further research is likely to have an important impact on our confidence in the estimate of effect and is likely to change the estimate) and very low (further research is likely to have an important impact on our confidence in the estimate of effect and is likely to change the estimate).


Original: The prevalence of adverse renal effects after treatment with cisplatin, carboplatin, ifosfamide, radiation therapy involving the kidney region, nephrectomy, or any combination of these, ranged from 0% to 84% depending on the study population, received treatment combination, reported outcome measure, follow-up duration and methodological quality.
Simplified: cisplatin, carboplatin, ifosfamide), radiation, or surgery involving the kidneys, or a combination of these treatments.


Original: A key method of surgical fixation is external fixation.
Simplified: A key method of surgical fixation is external fixation.


Original: The choice of IM or IV route of administration will depend on the available preparations, the dose to be administered and also on the patients' preferences.
Simplified: The choice of intramuscular or intravenous route of administration will depend on available preparations, the dose to be administered and also on the patients' preferences.


Original: However, long-term studies had equivocal or conflicting results regarding the effect on this outcome (low- to moderate-quality evidence).
Simplified: However, long-term studies had conflicting results regarding the effect on this outcome.


Original: The tooth is then moved into position covered by the palatal mucosa.
Simplified: After surgery, the tooth is then moved into position beneath the gum.


Original: We included three studies, involving 146 participants.